# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleMapsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo',
            name='firm',
        ),
    ]
