# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0034_firma'),
        ('googleMapsAPI', '0002_remove_geo_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicePr.Firma'),
        ),
    ]
