# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicePrMail', '0003_offertenanfrage_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offertenanfrage',
            name='branche',
        ),
    ]
