# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePrMail', '0005_auto_20171218_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempMail', models.EmailField(db_index=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='firmeneintrag',
            name='eMail',
            field=models.EmailField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offertenanfrage',
            name='eMail',
            field=models.EmailField(db_index=True, max_length=200, null=True),
        ),
    ]
