# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePrMail', '0006_auto_20180102_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmeneintrag',
            name='beschreibung',
            field=models.TextField(null=True),
        ),
    ]
