# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Umzug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
