# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baufirma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gartenbau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Immobilien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reinigung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sanitaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schreiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200, null=True)),
                ('firm_adress', models.CharField(max_length=200, null=True)),
                ('firm_plz', models.CharField(max_length=200, null=True)),
                ('firm_homepage', models.CharField(max_length=200, null=True)),
                ('firm_logo', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
