# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0004_auto_20170405_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umzug',
            name='firm_logo',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='treasure_images'),
        ),
    ]
