# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0006_auto_20170406_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmeneintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('firma', models.CharField(max_length=200, null=True)),
                ('eMail', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
