# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0007_firmeneintrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmeneintrag',
            name='eMail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='firmeneintrag',
            name='firma',
            field=models.CharField(max_length=200),
        ),
    ]
