# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0008_auto_20170406_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmeneintrag',
            name='branche',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firmeneintrag',
            name='eMail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firmeneintrag',
            name='firma',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
