# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0013_auto_20170419_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmeneintrag',
            name='branche',
            field=models.CharField(choices=[('Umzug', 'Umzug'), ('Reingung', 'Reingung'), ('Maler', 'Maler'), ('Schreiner', 'Schreiner'), ('Sanitaer', 'Sanitaer'), ('Immobilien', 'Immobilien'), ('Gartenbau', 'Gartenbau'), ('Baufirma', 'Baufirma'), ('Catering', 'Catering'), ('Architekt', 'Architekt')], max_length=200),
        ),
    ]
