# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0014_auto_20170420_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffertAnfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('adress', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('tel', models.CharField(max_length=200, null=True)),
                ('branche', models.CharField(choices=[('Umzug', 'Umzug'), ('Reingung', 'Reingung'), ('Maler', 'Maler'), ('Schreiner', 'Schreiner'), ('Sanitaer', 'Sanitaer'), ('Immobilien', 'Immobilien'), ('Gartenbau', 'Gartenbau'), ('Baufirma', 'Baufirma'), ('Catering', 'Catering'), ('Architekt', 'Architekt')], max_length=200)),
                ('selected_firmen', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OfferAnfrage',
        ),
    ]
