# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0015_auto_20170420_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architekt',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='baufirma',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='catering',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='gartenbau',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='immobilien',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='maler',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='reinigung',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='sanitaer',
            name='firm_logo',
            field=models.ImageField(upload_to='treasure_images'),
        ),
    ]
