# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0016_auto_20170425_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maler',
            name='firm_plz',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schreiner',
            name='firm_plz',
            field=models.IntegerField(null=True),
        ),
    ]
