# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0019_auto_20170425_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='architekt',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baufirma',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='catering',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gartenbau',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='immobilien',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maler',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reinigung',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sanitaer',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schreiner',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='umzug',
            name='firm_ort',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
