# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0020_auto_20170425_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='umzug',
            name='firm_beschreibung',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
