# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0023_auto_20170712_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('plz', models.IntegerField(db_index=True, max_length=200, null=True)),
                ('ort', models.CharField(db_index=True, max_length=200, null=True)),
                ('beschreibung', models.TextField()),
                ('eMail', models.CharField(db_index=True, max_length=200, null=True)),
                ('homepage', models.CharField(db_index=True, max_length=200, null=True)),
                ('firm_logo', models.ImageField(db_index=True, upload_to=b'treasure_images')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicePr.Branchen')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(db_index=True, max_length=200, null=True)),
                ('lat', models.CharField(db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicePr.Geo'),
        ),
    ]
