# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0024_auto_20170811_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='geo',
        ),
    ]
