# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0026_auto_20170811_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffertenAnfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('plz', models.IntegerField(db_index=True)),
                ('ort', models.CharField(db_index=True, max_length=200, null=True)),
                ('tel', models.CharField(db_index=True, max_length=200, null=True)),
                ('beschreibung', models.TextField()),
                ('eMail', models.CharField(db_index=True, max_length=200, null=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicePr.Branchen')),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='geo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicePr.Geo'),
            preserve_default=False,
        ),
    ]
