# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0030_delete_offertanfrage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geo',
            name='firm',
        ),
        migrations.DeleteModel(
            name='Geo',
        ),
    ]
