# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0031_auto_20170818_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Architekt',
        ),
        migrations.DeleteModel(
            name='Baufirma',
        ),
        migrations.DeleteModel(
            name='Catering',
        ),
        migrations.DeleteModel(
            name='Firmeneintrag',
        ),
        migrations.DeleteModel(
            name='Gartenbau',
        ),
        migrations.DeleteModel(
            name='Immobilien',
        ),
        migrations.DeleteModel(
            name='Maler',
        ),
        migrations.DeleteModel(
            name='Reinigung',
        ),
        migrations.DeleteModel(
            name='Sanitaer',
        ),
        migrations.DeleteModel(
            name='Schreiner',
        ),
        migrations.DeleteModel(
            name='Suche',
        ),
        migrations.DeleteModel(
            name='Umzug',
        ),
        migrations.AlterField(
            model_name='firma',
            name='plz',
            field=models.CharField(db_index=True, max_length=5, null=True),
        ),
    ]
