# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleMapsAPI', '0002_remove_geo_firm'),
        ('servicePr', '0032_auto_20171008_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='branche',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
    ]
