# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0033_auto_20171027_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('plz', models.CharField(db_index=True, max_length=5, null=True)),
                ('ort', models.CharField(db_index=True, max_length=200, null=True)),
                ('beschreibung', models.TextField()),
                ('eMail', models.CharField(db_index=True, max_length=200, null=True)),
                ('homepage', models.CharField(db_index=True, max_length=200, null=True)),
                ('firm_logo', models.ImageField(db_index=True, upload_to='treasure_images')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicePr.Branchen')),
            ],
        ),
    ]
