# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePr', '0034_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='eMail',
            field=models.EmailField(db_index=True, max_length=200, null=True),
        ),
    ]
